project: default
source:
  repoURL: https://github.com/sudhishmk/argocdexamples.git
  path: predeletehook/app
  targetRevision: main
destination:
  server: https://kubernetes.default.svc
  namespace: openshift-gitops
syncPolicy:
  automated:
    prune: true
    selfHeal: true
    enabled: false
  syncOptions:
    - CreateNamespace=true
ignoreDifferences:
  - kind: Deployment
    jsonPointers:
      - /spec/template/spec/containers/0/image

