apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: predelete-demo
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/YOUR_ORG/predelete-demo
    targetRevision: main
    path: .
  destination:
    server: https://kubernetes.default.svc
    namespace: predelete-demo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

